fix(export): Filter export for pre required filters
commutatus/spotlight-search pull request #36
Opened 2020-10-08 15:36 UTC by viveckadhriyaa

2020-10-21 17:18 UTC, sajinmp commented on lib/spotlight_search/exportable_columns_v2.rb
> +      def default_scopes_for_export(*filter_scopes)
If an array is needed, `filter_scopes` is enough bro. [*filter_scopes] and filter_scopes are same if it's an array.

2020-10-21 17:19 UTC, sajinmp requested changes
One change bro

2020-10-21 17:19 UTC, sajinmp commented on lib/spotlight_search/exportable_columns_v2.rb
> +        self.default_filters = [*filter_scopes]
If an array is needed, filter_scopes is enough bro. [*filter_scopes] and filter_scopes are same if it's an array.

2020-10-22 17:10 UTC, camiloforero commented
I agree with Sajimp's change. And other than that everything looks straightforward and idiomatic. If it works in practice, codewise it's good to go

2020-11-24 07:08 UTC, merged